### ISSUE TITLE
Feature request: Ability to choose how much bandwidth jotta-cli should consume

### ISSUE THREAD

**Issue by Soerboe** [jotta/jotta-cli-issues#21]
Currently jotta-cli utilizes the whole upload bandwidth capacity which has the effect that other uses of the Internet connection are very slow/useless until jotta-cli is done backing up.

It would be very useful to set that jotta-cli should only use e.g. 50% of the available bandwidth capacity.

**Comment by carestad** [comment]
Missing the same here. Been trying to get it working with `trickle` but have not been successful yet.

**Comment by Kimbsen** [comment]
We plan on adding this. I cannot promise any timeframe, but its going to happen.

**Comment by jinie** [comment]
i'm looking forward to this feature, but for now i've just added a "jotta-cli pause 24h" and "jotta-cli resume" to my crontab, to schedule uploading to run at night.

I'd also like to see an option to set the maximum number of threads used for uploading, assuming one file upload per thread.
I'm running jotta-cli on my Synology NAS through docker, and it's really punishing the drives while uploading-

**Comment by who8mypnuts** [comment]
I'd very much like to see this feature too. Just migrated from windows after purchasing another year subscription to Jotta and now the service is effectively useless to me because the cli client consumes all of our bandwidth making the internet unusable when it runs. I'm requesting please that this be a priority.

**Comment by CorMelse** [comment]
i agree, please add an option for this

**Comment by meetyourlaser** [comment]
Is there any progress here? It is frustrating having jotta-cli occupying all the upload bandwidth.

**Comment by who8mypnuts** [comment]
Since nothing is being done here, I'm attempting to find some solutions on my own. I've found a program called trickle that rate limits command line apps. The problem is that jottad is a service and doesn't allow trickle to function as normal. If anyone has any insights as to how jotta-cli is initiated, please let me know. I'll be digging a little more on my own and see what I can rig up.

**Comment by who8mypnuts** [comment]
Okay. Figured it out.
**Install Trickle.**

This is the directory that contains the file that needs modification:
`/usr/share/jottad/upstart/0.6.5/files/etc/init/`
edit jottad.conf  (likely line 17) to have the following:
`exec chroot --userspec jottad:jottad / /usr/bin/trickle -d20 -u20 -s /usr/bin/jottad  >> /var/log/jottad-stdout.log 2>> /var/log/jottad-stderr.log`

-d is download speed in Kbs.
-u is upload speed in Kbs
-s is to use in standalone mode.

This is the first time in months I can use jotta backup and browse the internet at the same time! I'm even posting this with it running and the page loads! Amazing!

**Comment by coopersimon** [comment]
You can do this with `jotta-cli config set downloadrate [desiredRate]`
