### ISSUE TITLE
FRQ: One-shot backup with feedback

### ISSUE THREAD

**Issue by bertmelis** [jotta/jotta-cli-issues#33]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):** 0.4.4986

**Description of problem:**
I want to backup my server files (configuration, db-dumps...). However, jotta-cli now acts as a continuous sync service and fails when trying to sync files that have shared access (permission denied error).
In case of a DB-dump, I don't know when the dump is synced so I'm unable to restart the server unless personally/manually verified.

**Expected:**
to be able to use a (scripted) one-shot backup: stop my server, dump DB, backup dumps (wait until backup is completed) and restart server

**Comment by Kimbsen** [comment]
I'm not entirely sure what you mean the problem is. Is it that jottad is unable to backup the database files as they have a share-lock on them while the database is running? And you want to just run backup after the database dump has been generated and before restarting the database? Or something like that?

Jottad runs scans of folders added to backup on an interval. This is configurable using ```jotta-cli config set scaninterval 10m``` or some other golang time.Duration. ```30m, 1h, 25h ```etc should also work. 

If that won't work for you you could always script backup of these files using the archive command. 
```jotta-cli archive /path/to/dumpfile1 && jotta-cli archive /path/to/dump2``` or something to that effect. 

We do plan on adding the ability to archive a folder so you can one-shot backup a directory-tree. But we don't have any eta for when that will be added.

**Comment by bertmelis** [comment]
Indeed, I want to backup a folder structure using a script (and cron or systemd):

But do I understand correct that I could script this by iterating over the directory structure and use the `archive` option?

- stop my server
- for each file in my directory: `jotta-cli archive /path/to/file`
- restart the server

Does `jotta-cli archive` return immediately or does it block untill the has actually archived (and uploaded)?

**Comment by Kimbsen** [comment]
Yeah, that should work.

jotta-cli archive does block until the file is uploaded.

**Comment by bertmelis** [comment]
sweet! Then it's time to upgrade to a paid subscription :smile:

**Comment by bertmelis** [comment]
Euh wait, does the option "archive" remove my local copy? because that's not what I want.

**Comment by Kimbsen** [comment]
No, it does not delete the file you archive.

**Comment by bertmelis** [comment]
Thanks!
