### ISSUE TITLE
Backup folders with same name located on different partitions

### ISSUE THREAD

**Issue by paalge** [jotta/jotta-cli-issues#36]
Thank you for this tool, it looks to be a really good tool.

**jotta-cli release (`jotta-cli version`):**
```
  jotta-cli     version 0.4.4986
  jottad        version 0.4.4986
  jottad        host    raman
  jottad        path    /usr/bin/jottad
  jottad        appdata /var/lib/jottad
```

**Description of problem:**
I've got two folders called `work`, located on two different partitions.
I do not want to add the whole partitions to the backup, only the folders. Currently the files end up in the same folder.

**Expected:**
For archive the `--remote` options works. It would be nice if it also worked for `add`, i.e.
`jotta-cli add work --remote workb`

**Comment by CorMelse** [comment]
I support this request, would be very helpful if this option is added to the "jotta-cli add" function

**Comment by Kimbsen** [comment]
Yeah, this seems like something we should support. 

We'll look into adding this in a future release.

**Comment by cvillabrille** [comment]
It must be a joke... I have opened the same question today in the Forum :)

Support has redirected me to this forum. Hence, let me add here the question also.

Linux Client - Can I upload folders with a different naming?
I'm trying to upload a generic folder "home" but I do not want to save it with this name, as I already have some other called home as well. Looks the command does not upload the files with my referred name, or I'm not able to understand what --remote means.

As per the help... --remote Where you want it?

Well, I want it in a different folder name. I have tried with ... jotta-cli add /home --remote "duplicacy" or with jotta-cli add /home --remote /duplicacy/ or some more combinations of this. Is that possible? I mean, Can I upload a folder with a different naming?

Otherwise, what's the meaning of --remote then?

**Comment by Kimbsen** [comment]
We have not added ```jotta-cli add /path --remote name``` yet. 
There is a ``` jotta-cli archive /path/to/file --remote /remote/path``` but that is only for uploading single files to the archive.

We will add the former, hopefully in the next release of jotta-cli.

**Comment by cvillabrille** [comment]
Thanks for you quick reply. I did not realize it was not an option, the command run with no error or no messages that this modifier was not an option.

Anyhow, any estimation on when the next release will be available?.

Thanks for the good work with the tool, keep doing such a right thing.

**Comment by Kimbsen** [comment]
In version 0.5 we added ```jotta-cli add /path/to/folder --name name``` which allows you to add folders with the same name to backup.
